In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv('practiceDataset.csv')

In [4]:
dataset.shape

(1460, 81)

In [5]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [6]:
dataset.columns[dataset.isna().any()]

Index(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence',
       'MiscFeature'],
      dtype='object')

In [7]:
dataset=dataset.drop(['Alley','PoolQC','Fence','MiscFeature','Id','MasVnrType'],axis=1)

In [8]:
dataset.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [9]:
X=dataset.iloc[:,:-1]
Y=dataset['SalePrice']

In [10]:
X.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,61,0,0,0,0,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,42,0,0,0,0,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,35,272,0,0,0,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,84,0,0,0,0,0,12,2008,WD,Normal

In [11]:
def encoding(X):
  from sklearn.preprocessing import LabelEncoder
  columnstoencode=list(X.select_dtypes(include=['category','object']))
  le= LabelEncoder()
  for i in columnstoencode:
    try:
        X[i]=le.fit_transform(X[i])
    except:
        continue
  return X

In [12]:
encoding(X)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,3,65.0,8450,1,3,3,0,4,0,...,61,0,0,0,0,0,2,2008,8,4
1,20,3,80.0,9600,1,3,3,0,2,0,...,0,0,0,0,0,0,5,2007,8,4
2,60,3,68.0,11250,1,0,3,0,4,0,...,42,0,0,0,0,0,9,2008,8,4
3,70,3,60.0,9550,1,0,3,0,0,0,...,35,272,0,0,0,0,2,2006,8,0
4,60,3,84.0,14260,1,0,3,0,2,0,...,84,0,0,0,0,0,12,2008,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,3,62.0,7917,1,3,3,0,4,0,...,40,0,0,0,0,0,8,2007,8,4
1456,20,3,85.0,13175,1,3,3,0,4,0,...,0,0,0,0,0,0,2,2010,8,4
1457,70,3,66.0,9042,1,3,3,0,4,0,...,60,0,0,0,0,2500,5,2010,8,4
1458,20,3,68.0,9717,1,3,3,0,4,0,...,0,112,0,0,0,0,4,2010,8,4
1459,20,3,75.0,9937,1,3,3,0,4,0,...,68,0,0,0,0,0,6,2008,8,4

In [13]:
t=list(X.columns[X.isna().any()])

In [14]:
for i in t:
    X[i]=X.fillna(X[i].mean)

In [15]:
X.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,3,60,8450,1,3,3,0,4,0,...,61,0,0,0,0,0,2,2008,8,4
1,20,3,20,9600,1,3,3,0,2,0,...,0,0,0,0,0,0,5,2007,8,4
2,60,3,60,11250,1,0,3,0,4,0,...,42,0,0,0,0,0,9,2008,8,4
3,70,3,70,9550,1,0,3,0,0,0,...,35,272,0,0,0,0,2,2006,8,0
4,60,3,60,14260,1,0,3,0,2,0,...,84,0,0,0,0,0,12,2008,8,4
5,50,3,50,14115,1,0,3,0,4,0,...,30,0,320,0,0,700,10,2009,8,4
6,20,3,20,10084,1,3,3,0,4,0,...,57,0,0,0,0,0,8,2007,8,4
7,60,3,60,10382,1,0,3,0,0,0,...,204,228,0,0,0,350,11,2009,8,4
8,50,4,50,6120,1,3,3,0,4,0,...,0,205,0,0,0,0,4,2008,8,0
9,190,3,190,7420,1,3,3,0,0,0,...,4,0,0,0,0,0,1,2008,8,4

In [16]:
X.columns[X.isna().any()]

Index([], dtype='object')

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
model1=RandomForestRegressor()
model=LinearRegression()

In [18]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,random_state=None)
for train_index , test_index in skf.split(X,Y):
    x1_train,x1_test=X.iloc[train_index],X.iloc[test_index]
    y1_train,y1_test=Y.iloc[train_index],Y.iloc[test_index]

C:\Users\hp\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

In [19]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x1_train=scaler.fit_transform(x1_train)
x1_test=scaler.transform(x1_test)
model.fit(x1_train,y1_train)
model1.fit(x1_train,y1_train)

RandomForestRegressor()

In [20]:
 d=model.predict(x1_test)

In [21]:
e=np.array(y1_test)

In [22]:
print(np.concatenate((d.reshape(len(d),1),e.reshape(len(e),1)),1))

[[123684.75390364 134800.        ]
 [131631.31101625  98600.        ]
 [197289.71231274 204750.        ]
 [242640.54363091 259500.        ]
 [ 82437.61966225 103200.        ]
 [377685.25888168 475000.        ]
 [120365.77240161 153337.        ]
 [106509.7009125  104000.        ]
 [138511.7719505  143900.        ]
 [220602.19023855 231500.        ]
 [321808.64791099 276000.        ]
 [172986.84657899 179500.        ]
 [178696.52515926 164700.        ]
 [135339.75146867 153575.        ]
 [130480.08747383  89500.        ]
 [281245.11761252 301000.        ]
 [148319.92656916 145250.        ]
 [310945.85693788 377426.        ]
 [298274.59655991 266000.        ]
 [102167.81724196 134432.        ]
 [ 46236.95343003  61000.        ]
 [ 98335.35471923  76000.        ]
 [146090.75755893 169500.        ]
 [261233.52766378 228000.        ]
 [218949.64618457 195400.        ]
 [113720.60676639  62383.        ]
 [111742.10018069  89471.        ]
 [187854.8744737  172785.        ]
 [244435.62840084 289000.        ]
 [189496.81719669 211000.        ]
 [ 57095.66051727 106250.        ]
 [178879.68360425 159000.        ]
 [232238.7918343  179665.        ]
 [257643.70115255 255500.        ]
 [269125.73445274 284000.        ]
 [136006.00173435 142600.        ]
 [151481.48158298 164500.        ]
 [ 83418.64105744  79500.        ]
 [218295.98331304 205000.        ]
 [ 53399.0859245   75500.        ]
 [309151.1565791  305000.        ]
 [ 43599.329357    67000.        ]
 [155047.20828701 168500.        ]
 [126974.39269476 139400.        ]
 [237796.10491966 226000.        ]
 [141231.89120394 143250.        ]
 [109704.42726191 108000.        ]
 [151247.51565906 145500.        ]
 [324646.17456068 402000.        ]
 [243322.31016153 257500.        ]
 [196243.02771445 221000.        ]
 [153502.83537    141000.        ]
 [466750.91586389 755000.        ]
 [111058.79273515 141500.        ]
 [ 88658.81520723 102776.        ]
 [100511.43486374 124500.        ]
 [235900.17690566 222500.        ]
 [112870.41471313 108000.        ]
 [242607.58338315 239900.        ]
 [133393.29150519 132000.        ]
 [186478.19792004 179000.        ]
 [252275.8688023  260400.        ]
 [100645.04668391  98000.        ]
 [ 60210.71475356  96500.        ]
 [167994.26230275 156000.        ]
 [296340.55593592 337000.        ]
 [111539.44485176 114500.        ]
 [237985.31087477 221500.        ]
 [245228.97557189 269790.        ]
 [222686.17169093 194500.        ]
 [237486.86461013 227680.        ]
 [196297.49641223 183000.        ]
 [366352.97991031 385000.        ]
 [164318.87707861 157500.        ]
 [107945.10573753 141000.        ]
 [122955.36335156 131500.        ]
 [158025.35870999 152000.        ]
 [206927.93428441 250580.        ]
 [104261.43022217 109500.        ]
 [137032.10093761 116000.        ]
 [147038.29256071 148000.        ]
 [120963.0016599  118500.        ]
 [243701.75451776 328900.        ]
 [182706.7802595  149500.        ]
 [190961.08289094 172500.        ]
 [ 78230.51928573 106500.        ]
 [402866.88008685 611657.        ]
 [145287.44414689 153000.        ]
 [ 30535.3202994   35311.        ]
 [197592.26296626 169990.        ]
 [214551.44823672 207500.        ]
 [169483.69897379 175000.        ]
 [266378.51846888 236500.        ]
 [227584.54760814 222000.        ]
 [328211.63098767 320000.        ]
 [163595.52829824 150900.        ]
 [105543.11935642 150000.        ]
 [158710.66151462 124900.        ]
 [289363.62740334 270000.        ]
 [119535.3324523  119900.        ]
 [132753.61966225 132000.        ]
 [267682.96863191 272000.        ]
 [233235.02783028 214900.        ]
 [ 87357.25807036 110000.        ]
 [302113.1668876  336000.        ]
 [286581.12365825 348000.        ]
 [220305.42675769 187000.        ]
 [ 74285.43486374  82000.        ]
 [ 99528.85870999 100000.        ]
 [ 86973.29941884  85000.        ]
 [194127.56698648 213490.        ]
 [118510.9949022   87000.        ]
 [ 64981.22024178  84000.        ]
 [253412.91315618 287000.        ]
 [ 76591.44414689  97000.        ]
 [159899.71902386 155000.        ]
 [125825.43950531 139600.        ]
 [139864.12025043 144500.        ]
 [257716.82009249 255000.        ]
 [217744.29118634 185850.        ]
 [184082.49170678 220000.        ]
 [155867.88082498 110500.        ]
 [209941.4065894  192000.        ]
 [179114.32923962 187500.        ]
 [263374.83038662 252000.        ]
 [ 95348.18486374 128000.        ]
 [125399.8425029  135000.        ]
 [160930.56177281 159500.        ]
 [103583.61966225 106000.        ]
 [279543.33409648 280000.        ]
 [203968.70060485 205000.        ]
 [118201.69117443 129900.        ]
 [ 83017.09048317 118000.        ]
 [193145.90491931 163900.        ]
 [157665.47738015 135000.        ]
 [160164.79115821 117500.        ]
 [227098.09332054 196000.        ]
 [ 92451.34942685  80000.        ]
 [204417.53572044 180000.        ]
 [167113.68486374 174500.        ]
 [209036.459888   185000.        ]
 [120347.88104637 108959.        ]
 [193934.39306808 173000.        ]
 [213904.30253146 200500.        ]
 [298535.98207359 285000.        ]
 [115208.47806346 154900.        ]
 [ 73387.44620766  93000.        ]
 [104441.70413366  95000.        ]
 [187733.87423772 168000.        ]
 [155119.86899165 165000.        ]
 [141244.31441733 158000.        ]
 [183372.20622752 176000.        ]
 [136164.21415063 148000.        ]
 [209712.09626218 213000.        ]
 [147516.65760468 153500.        ]
 [120466.67931349 107000.        ]
 [147645.50637592 140000.        ]
 [234807.95225811 164000.        ]
 [ 79808.84292751 113000.        ]
 [115696.04212997 145000.        ]
 [122042.61902392 134500.        ]
 [105001.61502068 125000.        ]
 [242498.04693722 229456.        ]
 [ 84704.98209887  91500.        ]
 [100697.31565782 115000.        ]
 [131331.02571709 134000.        ]
 [167189.88358696 143000.        ]
 [227282.25543474 184000.        ]
 [136218.29827249 145000.        ]
 [234812.67954762 214000.        ]
 [109187.51565906 127000.        ]
 [122552.02217623 138887.        ]
 [225176.08593551 195000.        ]
 [152909.3527904  142500.        ]
 [225437.65535866 224900.        ]
 [184323.37862541 170000.        ]
 [194831.57154502 178000.        ]
 [178947.73482772 129500.        ]
 [283369.36335156 244000.        ]
 [114439.42487155 130000.        ]
 [293378.20099609 301500.        ]
 [204257.70705687 190000.        ]
 [168741.42600064 151000.        ]
 [121542.92766891 161500.        ]
 [172739.21280119 181000.        ]
 [336870.83506442 381000.        ]
 [139996.98780403 139000.        ]
 [147652.10573753 137000.        ]
 [162458.3270831  162000.        ]
 [248643.81064856 237000.        ]
 [223702.07218118 180000.        ]
 [119035.54214778 139000.        ]
 [120644.32341118 132500.        ]
 [170854.54869554 143000.        ]
 [170207.37610696 190000.        ]
 [151768.42652923 180500.        ]
 [104203.26726926 119500.        ]
 [125066.0408091  107500.        ]
 [202286.15160875 162900.        ]
 [126492.19500199 115000.        ]
 [158596.36936198 155000.        ]
 [140765.22804726 140000.        ]
 [161175.2960348  154000.        ]
 [236878.81914689 225000.        ]
 [300405.78112942 290000.        ]
 [163557.23529471 130000.        ]
 [315731.92324672 325000.        ]
 [206740.08233714 202500.        ]
 [163884.10675979 147000.        ]
 [292173.69942683 302000.        ]
 [312862.23632443 333168.        ]
 [ 53891.52030064  72500.        ]
 [248031.54375201 190000.        ]
 [106304.09386354  82500.        ]
 [269697.8524511  147000.        ]
 [ 70113.22434951  79000.        ]
 [240209.20308023 256000.        ]
 [261145.81764543 227000.        ]
 [118158.69117443 132500.        ]
 [100223.44414689 100000.        ]
 [ 93638.0213229  125000.        ]
 [132156.77351599 135000.        ]
 [239327.68251286 200000.        ]
 [112319.695816   128500.        ]
 [179517.104182   155000.        ]
 [246968.34746565 228500.        ]
 [164657.20343003 177000.        ]
 [167818.07854413 122000.        ]
 [202756.93022217 200000.        ]
 [174880.01024186 171000.        ]
 [141182.69466664 134900.        ]
 [337405.59306463 410000.        ]
 [214564.03087043 170000.        ]
 [ 99975.50637592 110000.        ]
 [143579.36335156 149900.        ]
 [340686.83841182 315000.        ]
 [189939.25551959 189000.        ]
 [264851.03260136 260000.        ]
 [114933.90305056 104900.        ]
 [122112.56232347 127000.        ]
 [152835.61943868 144000.        ]
 [256778.78149098 232000.        ]
 [203694.0672431  165500.        ]
 [405784.92641029 466500.        ]
 [255003.77675408 250000.        ]
 [257061.05153136 239000.        ]
 [ 84767.12816474  91000.        ]
 [125932.63619621 117000.        ]
 [162842.37239333 167500.        ]
 [189136.64140901 157000.        ]
 [311932.91304755 250000.        ]
 [132097.62430382 131000.        ]
 [231023.6548202  235000.        ]
 [138747.8268833  163000.        ]
 [293273.05953182 281213.        ]
 [180224.7581896  160000.        ]
 [116598.0998528  137500.        ]
 [131233.70592047 138000.        ]
 [108099.77814969 120000.        ]
 [ 97295.37575355 105000.        ]
 [256663.04495089 275000.        ]
 [121067.04225957 133000.        ]
 [217766.50461912 215000.        ]
 [217643.28597533 230000.        ]
 [133285.9255806  140000.        ]
 [ 89353.93950531  90000.        ]
 [122587.0576722  122500.        ]
 [130716.32120354 124000.        ]
 [229907.78999666 223000.        ]
 [170277.68114006 179900.        ]
 [130941.81752158 127500.        ]
 [148371.71880029 136500.        ]
 [142707.14479417 144000.        ]
 [182389.2983166  142000.        ]
 [131765.78422535 140000.        ]
 [111363.65147685 119000.        ]
 [ 80323.10109596  64500.        ]
 [196971.90458378 186500.        ]
 [172865.45014762 160000.        ]
 [192253.57964056 174000.        ]
 [200087.34352663 191000.        ]
 [209083.90065893 179600.        ]
 [127844.38268105 129000.        ]
 [262171.81909747 240000.        ]
 [ 87149.84905805 112000.        ]
 [ 98001.81674967 136000.        ]
 [116274.37159447 145000.        ]
 [108045.17990935  84500.        ]
 [214379.84374151 185000.        ]
 [174200.13129153 175000.        ]
 [207346.36404002 210000.        ]
 [162529.12935293 147500.        ]]